title:            Here's to the crazy ones!
description:      Isaak Mogetutu. Software Developer living in Nairobi. I love cycling and taking nice little photos.
url:              http://mogetutu.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
folder:           stuff
rdiscount:
  extensions:     [smart]
google_analytics: UA-27869799-1
timezone:         Africa/Nairobi
paginate: 5
links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/mogetutu
  - name:         Twitter
    url:          http://twitter.com/mogetutu
  - name:         Instagram
    url:          http://instagram.com/mogetutu
